### ISSUE TITLE
Error urllib.error.URLError: <urlopen error [WinError 10060

### ISSUE THREAD

**Issue by AhrimanSefid** [Mizogg/4Bitcoin#1]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AhrimanSefid\Desktop\BTC\4Bitcoin-main\4Bitcoin.py", line 45, in <module>
    contents = urllib.request.urlopen("https://blockchain.info/q/getreceivedbyaddress/" + uaddr).read()
  File "C:\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by Mizogg** [comment]
Hi There, I'll try and help.  Did it start working then stop? Running more than one instance? reduced sleep time to 0?  could be 2 main reasons why this is not working. 
1. You have done to many API requests from https://blockchain.info and they temporary blocked your IP. If you have VPN please try changing your IP to see if this helps.
2. The error code 10060 means it cannot connect to the remote peer. It might be because of the network problem or mostly your setting issues, such as proxy setting.

I hope this helps.

**Comment by AhrimanSefid** [comment]
thank you.
but can video step by step.

**Comment by Mizogg** [comment]
Running Windows 11 python 3.10

pip install  bitcoinaddress
pip install rich

Edit line 5, 6 & 78 to setup for gmail email

https://user-images.githubusercontent.com/88630056/144656593-391ab0e1-bcf3-4485-b295-5a096ce707c0.mp4

KeyboardInterrupt was me pressing crtl+c to stop the scan and then start new scan/range

Something went wrong... Error as Gmail details invalid and could not send the email. But still writes and save to file.

**Comment by AhrimanSefid** [comment]
very thank you.
I need to use your application for BTC/ETH2, I have approximately 30 api for ethplorer.io.
Also, I need your help regarding BTC.
Your help is really appreciated, in addition if you guide me to improve it and run it strongly I will be grateful.

**Comment by AhrimanSefid** [comment]
can add btc balance checker
def bitflyer(address):
        r = requests.get("https://chainflyer.bitflyer.jp/v1/address/" + address)
        b = json.loads(r.text)
        return b['unconfirmed_balance']

def spectro(address):
        r = requests.get("https://explorer.spectrocoin.com/api/addr/" + address)
        b = json.loads(r.text)
        return b['totalReceived']

def blockchain(address):
        r = requests.get("https://blockchain.info/ja/q/getreceivedbyaddress/" + address)
        return r.text

def chainz(address):
        r = requests.get("https://chainz.cryptoid.info/btc/api.dws?q=getreceivedbyaddress&a=" + address)
        return r.text

def chainso(address):
        r = requests.get("https://chain.so/api/v2/get_address_balance/BTC/" + address)
        b = json.loads(r.text)
        return b['data']['confirmed_balance']

def btccom(address):
        r = requests.get("https://chain.api.btc.com/v3/address/" + address)
        b = json.loads(r.text)
        return b['data']['received']

and multi api ethplorer.io

**Comment by Mizogg** [comment]
Great to Have some more API details to add. I may add these in later programs. 

I like to edit and improve others or share ideas. But the best part is learning and seeing what I can make next. Please check my site https://mizogg.co.uk/ for help on running python programs or join any of the Telegram groups that im in some question already asked and answered.
Crypto Crackers https://t.me/CryptoCrackersUK
Bitcoin private keys & crypto puzzles https://t.me/bitcoin_keys


  If you want to fork and improve please go ahead.
