### ISSUE TITLE
miz4(new) Error

### ISSUE THREAD

**Issue by AhrimanSefid** [Mizogg/4Bitcoin#2]
←[36m  [TIMING]> [2021-12-04 16:16:44.579974] ----> Start Program
←[0;0;39m
←[36mmiz4.py---←[31mRandom Scan for BTC\ETH\DOGE Addresses Transactions/Balance/Total Received Ammount-------mizogg.co.uk←[36m---miz4.py←[0;0;39m2021-12-04 16:16:44.579974
Best Run on 1 thread to not block API but you can try more : How many threads to run?:  1
ethplorer.io API KEY Paste here (Create free account to get API key) :  7PWNNIPH8F8HEMCI3AZIHWNUB46VICMP67
←[0;33mStart search... Pick Range to start (Example Puzzle 64 starting Range 18446744073709551615 ):←[0;0;39m
'start range Min 1-115792089237316195423570985008687907852837564279074904382605163141518161494335 -> 1
stop range Max 115792089237316195423570985008687907852837564279074904382605163141518161494336 -> 115792089237316195423570985008687907852837564279074904382605163141518161494336
←[0;35mHappy Hunting and Good Luck, Starting search... Please Wait ←[0;0;39m
===============================================================================
Exception in thread Thread-1 (seek):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AhrimanSefid\Desktop\BTC\4Bitcoin-main\miz4(new).py", line 82, in seek
    balances = dict(ress)["countTxs"]
KeyError: 'countTxs'

 ←[36m  [TIMING]> [2021-12-04 16:17:10.339580] ----> End Program
←[0;0;39m

 ←[31m [TIMING]> Elapsed time ==> 0:00:25.759606
←[0;0;39m

**Comment by AhrimanSefid** [comment]
 Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 82, in seek
    balances = dict(ress)["countTxs"] 
KeyError: 'countTxs'

**Comment by AhrimanSefid** [comment]
https://replit.com/@Amir-HosseinH11/eth-1#main.py

**Comment by Mizogg** [comment]
This need an API Key. Your API Key is invalid. Should look something like EB-iTz2Z-c45JOHN-Usj5q

![image](https://user-images.githubusercontent.com/88630056/144743737-a51c0597-22e3-4773-ade2-98e2408c0678.png)

Ethplorer only give you 5 request on freekey. If you create a free account on https://ethplorer.io/  you get 10,000 request a day

Info read https://github.com/Mizogg/ETH-ON-ETH-OFF or join https://t.me/CryptoCrackersUK
1. Number of CPU for multi proccessing
2. Insert API Key you can create 2 per account. Multi Accounts= Multiple API keys.
Remove # to make lines work insert your API key
3. pick or edit this line # if needed and use line below for 10.
4. Range for scanning
I think best 1 api = 1 cpu for my laptop I have 6 API's and run 6CPU

I will add some of this to older prgrams to make faster api requests.
![image](https://user-images.githubusercontent.com/88630056/144743628-b7b6be68-d058-40a0-a84f-97fe0d20274b.png)

Check Private Keys from File convert to Address and check Transactions. Online API Get FREE API KEY from https://ethplorer.io/

**Comment by AhrimanSefid** [comment]
sorry my api for https://etherscan.io/.

**Comment by AhrimanSefid** [comment]
C:\Users\AhrimanSefid\Desktop\BTC\ETH-ON-ETH-OFF-main>ethon.py
Process Process-1:  :   0xd0cf314f98d6709d71acb3e2ab977f5099f691fb   : TX =  0
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AhrimanSefid\Desktop\BTC\ETH-ON-ETH-OFF-main\ethon.py", line 108, in seek
    TXS = dict(ress)["countTxs"]
KeyError: 'countTxs'
Process Process-2:  :   0xad80b8740b47c8ec11e65e2cb826baa6dea34744   : TX =  0
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AhrimanSefid\Desktop\BTC\ETH-ON-ETH-OFF-main\ethon.py", line 108, in seek
    TXS = dict(ress)["countTxs"]
KeyError: 'countTxs'
